### ISSUE TITLE
How to catch timeout error?

### ISSUE THREAD

**Issue by altakhirov** [mvantellingen/python-zeep#1181] opened 2021-01-07 17:28 UTC
Hi everyone!
Sometimes request to SOAP service is in pending status for a long time, so I have set up timeout to 5 seconds. But I don't know how to handle it and return a message to user. After 5 seconds, I get the following error: `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /data/SomeServiceName?wsdl (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f33f0995af0>, 'Connection to example.com timed out. (connect timeout=5)'))` with error `500`.
```
try:
    response = client.service.soapMsg_Receive(**request_data)
except Fault: # for zeep exceptions
    return {'status': 'error', 'detail': 'Some error here, try again.')}
except (requests.ConnectTimeout, urllib3.exceptions.ConnectTimeoutError): # obviously, not works
    return {'status': 'error', 'detail': 'Server error.')
```
Thanks for your time and help.

**Comment by alik472** [comment] 2021-01-20 12:30
You can do this maybe:
```
try:
    response = client.service.soapMsg_Receive(**request_data)
except Exception as e:
    return e
```

**Comment by altakhirov** [comment] 2021-01-21 09:23
@alik472 It doesn't work.

**Comment by marisn** [comment] 2021-02-03 09:29
> ```
> except (requests.ConnectTimeout, urllib3.exceptions.ConnectTimeoutError): # obviously, not works
> ```

There is an error in your code. It is `requests.exceptions.ConnectTimeout` and not `requests.ConnectTimeout`. If you do not care about the nature of network error, you can use bare `requests.exceptions.RequestException` that will catch all types of network communication errors. Although I would suggest to catch HTTP exceptions separately as then you can try to be polite and close connection.

Not a bug in zeep, although documentation could be improved with examples how to handle exceptions in zeep usage.

**Comment by altakhirov** [comment] 2021-02-03 11:06
@marisn Thank you for your answer. Even `except Exception` doesn't work.  I guess you can catch `requests.exceptions` if you are using `requests` to send requests.

**Comment by marisn** [comment] 2021-02-04 10:07
> @marisn Thank you for your answer. Even `except Exception` doesn't work. I guess you can catch `requests.exceptions` if you are using `requests` to send requests.

This statement is not true. We just had network outage and I fixed similar issue in a legacy code base to handle gracefully rainy days in the cloud. Double check your code! The error comes not from the code you posted but much earlier – wrap with try-except also call to zeep.Client.

**Comment by altakhirov** [comment] 2021-02-04 12:07
@marisn You are right! The line `client = Client(wsdl, transport=Transport(timeout=5))` was outside try block. My bad that first I thought it's enough to have `response` inside try block. Thank you very much.

**Comment by marisn** [comment] 2021-02-04 15:20
@altakhirov Please close this bug report as it is not a zeep bug.

**Closed** 2021-02-04 20:17 UTC
