### ISSUE TITLE
Arrays/sequences transferred incomplete (empty) to the server

### ISSUE THREAD

**Issue by Flauschbaellchen** [mvantellingen/python-zeep#435] opened 2017-05-10 06:32 UTC
This issue is maybe somewhat releated to #145.
However the former issue has already been closed so I hope you don't mind if I open a new one.

I have currently the problem that arrays/sequences are sent empty to the server:

WSDL (partly):
```xml
  <wsdl:message name="save_master_data">
    <wsdl:part name="atk" type="xsd:string">
    </wsdl:part>
    <wsdl:part name="type" type="xsd:string">
    </wsdl:part>
    <wsdl:part name="data" type="tns:masterObjectDataArray">
    </wsdl:part>
  </wsdl:message>

  <xs:complexType final="#all" name="masterObjectDataArray">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="item" nillable="true" type="tns:masterObjectData"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="masterObjectData">
    <xs:sequence>
      <xs:element name="id" type="xs:long"/>
      <xs:element minOccurs="0" name="name" type="xs:string"/>
      <xs:element name="alive" type="xs:boolean"/>
      <xs:element minOccurs="0" name="custom" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
```

Method called:
```python
objects = [
 client.type_factory('ns0').masterObjectData(id=1, name="Object1", alive=true, custom=""),
 client.type_factory('ns0').masterObjectData(id=2, name="Object2", alive=true, custom=""),
 client.type_factory('ns0').masterObjectData(id=3, name="Object3", alive=true, custom="")
]
client.save_master_data("foo", "bar", objects)
```
Request beeing sent:
```xml
<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
  <soap-env:Body>
    <ns0:save_master_data xmlns:ns0="http://example">
      <atk>foo</atk>
      <type>bar</type>
      <data/>
    </ns0:save_master_data>
  </soap-env:Body>
</soap-env:Envelope>
```

Python Debug (generation of objects seems to be successfull):
```python
print(repr(objects))
#==>
[{
    'id': 1,
    'name': 'Object1',
    'alive': True,
    'custom': "" },
{
    'id': 2,
    'name': 'Object2',
    'alive': True,
    'custom': "" },
[...] ]
```

Expected (afaik):
```xml
<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
  <soap-env:Body>
    <ns0:save_master_data xmlns:ns0="http://example">
      <atk>foo</atk>
      <type>bar</type>
      <data>
       <masterObjectData>
         <id>1</id>
         <name>Object1</name>
         <custom></custom>
       </masterObjectData>
        <masterObjectData>
          <id>2</id>
          <name>Object2</name>
          <custom></custom>
        </masterObjectData>
[...]
      </data>
    </ns0:save_master_data>
  </soap-env:Body>
</soap-env:Envelope>
```

**Comment by swarmer** [comment] 2017-05-10 13:11
I'm having the same problem (with different WSDL).

**Comment by swarmer** [comment] 2017-05-10 13:30
Turns out, you need to pass factory.masterObjectDataArray(objects). I wonder if there's room for special handling of such array arguments in the library, because it's very counterintuitive right now.

**Comment by mvantellingen** [comment] 2017-05-13 12:08
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by mvantellingen** [comment] 2017-05-14 11:57
Which version of zeep are you using? I' cant reproduce it so an example script is required here

**Comment by Flauschbaellchen** [comment] 2017-05-14 16:10
Thanks for your response. I'll get you an example script tomorrow.

**Comment by marquesds** [comment] 2017-05-16 17:13
I'm having the same problem here 😞

**Comment by marquesds** [comment] 2017-05-16 17:14
I think this may help:
https://github.com/mvantellingen/python-zeep/issues/145#issuecomment-299260771

**Comment by marquesds** [comment] 2017-05-16 21:17
This approach saved my life:
https://github.com/mvantellingen/python-zeep/issues/145#issuecomment-299317970

**Comment by wynandvdl** [comment] 2017-06-02 12:28
Hi,

I'm having the same problem. Populating values from Django into a dictionary and then iter over them into a formatted array. Zeep only takes the first item in the array

https://gist.github.com/wynandvdl/b8fb446f3dbacc749dec5c739fc62f2a

Here is the script I run for testing purposes

```
from zeep import Client
from lxml import etree

client = Client('http://integrator.eduprinters.co.za:16899/axis/services/DistributionWS?wsdl')

lineitem = []
items = '12345', 'test1'

for item in items:
	line_type = client.get_type('ns2:ArrayOf_tns3_SalesOrderLineCreateRequest')
	line = line_type({'itemCode': item})
	lineitem.append(line)

node = client.create_message(client.service, 'salesOrderCreate', accountNumber='1234', salesOrderLineCreateRequests=lineitem)

print(etree.tostring(node, pretty_print=True))
```

The array generated looks correct
```
>>> lineitem
[{
    'item': {
        'itemCode': '12345'
    }
}, {
    'item': {
        'itemCode': 'test1'
    }
}]
```
I'm running Zeep 2.0.0

**Comment by marquesds** [comment] 2017-06-02 13:57
@wynandvdl which zeep version are u using? I think this issue was fixed on version 2.0.0:
https://github.com/mvantellingen/python-zeep/blob/master/CHANGES

BTW, you can change your data structure to something like this:
https://github.com/mvantellingen/python-zeep/issues/435#issuecomment-301918382

**Comment by wynandvdl** [comment] 2017-06-05 09:13
Hi marquesds,

Seems I only needed the weekends rest.

I did the following and everything worked as it should.

```
for item in items:
	
	line = {'itemCode': item}
	lineitem.append(line)

lines = line_type(lineitem)
```


Thanks for the help.

**Comment by mvantellingen** [comment] 2017-07-08 07:59
Yeah the issue seems to be mainly that soap encodes arrays in a weird way. That's why you see a lot of times stuff like: 'results': ArrayOfStrings -> [string1, string2, ..]. 

It's mostly a documentation issue which i hope tol solve with #110 

Closing this for now as it seems to be solved and I need some order in the issue list :-)

**Closed by mvantellingen** 2017-07-08 07:59 UTC
Labels: needs-example-script

**Comment by 3UR** [comment] 2023-09-22 10:49
+1 for @marquesds solution, saved me from hours of trying to figure out why it didnt work 😅
