### ISSUE TITLE
How do I represent a global enum in my code?

### ISSUE THREAD

**Issue by abhidotnet** [mvantellingen/python-zeep#64] opened 2016-06-09 17:35 UTC
I have this call being made to a Soap service. This is a call from SoapUI.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wcf="http://wcf42.Services">
   <soapenv:Header/>
   <soapenv:Body>
      <wcf:Authenticate>
         <!--Optional:-->
         <wcf:userName>serviceUser</wcf:userName>
         <!--Optional:-->
         <wcf:userPwd>serviceUserPassword</wcf:userPwd>
         <!--Optional:-->
         <wcf:authenticationMode>Ldap</wcf:authenticationMode>
      </wcf:Authenticate>
   </soapenv:Body>
</soapenv:Envelope>
```
When I try to pass Ldap as a string, the code fails with this message.

`KeyError: u"No such type: u'{http://schemas.datacontract.org/2004/07Test.Framework./SysUtils}GlobalEnums.AuthenticationMode' (Only have {http://Test.Services}ServiceResult)"`

Is there any method to resolve this? I have attached the wsdl for this service.

[AuthenticateSvc.txt](https://github.com/mvantellingen/python-zeep/files/307559/AuthenticateSvc.txt)
ateSvc.txt)

**Comment by mvantellingen** [comment] 2016-06-09 20:00
Hiya, the wsdl seems invalid to me. Although it works in soap-ui it doesn't seem to follow the spec. The issue is that the various xsd:schemas in the wsdl don't import each other.

See also https://lists.w3.org/Archives/Public/www-ws-desc/2002Sep/0025.html

**Comment by mvantellingen** [comment] 2016-06-22 17:23
Should probably be fixed now btw. It turned out I was wrong about the wsdl beging invalid :P

**Closed** 2016-06-22 17:23 UTC
Labels: feedback-required, xsd

**Comment by abhidotnet** [comment] 2016-09-12 14:07
Let me give it a whirl and I shall get back to you. Thank You.
