### ISSUE TITLE
Error parsing WSDL

### ISSUE THREAD

**Issue by RafaelHarispe** [mvantellingen/python-zeep#626] opened 2017-11-29 13:55 UTC
Hi, I have some troubles to read an WSDL.
Im using zeep: 2.4.0

When I try to créate client
clienteAdaptor = Client('http://180.204.114.101:8080/WSService/WSService?wsdl')

Its returns: XMLSyntaxError: Invalid XML content received (Opening and ending tag mismatch: meta line 5 and head, line 6, column 9)

Nevertheless, the command: 
python -mzeep http://180.204.114.101:8080/WSService/WSService?wsdl
Looks to work fine, without send any error.

Thanks a lot!

[WSService.zip](https://github.com/mvantellingen/python-zeep/files/1513999/WSService.zip)

**Comment by RafaelHarispe** [comment] 2017-11-29 13:56
This is the output for the command:
python -mzeep http://180.204.114.101:8080/WSService/WSService?wsdl

Prefixes:
     xsd: http://www.w3.org/2001/XMLSchema
     ns0: http://ws.clients.channels.mw.ksit.com/

Global elements:
     ns0:wsExecute(ns0:wsExecute)
     ns0:wsExecuteResponse(ns0:wsExecuteResponse)


Global types:
     xsd:anyType
     ns0:wsExecute(channel: xsd:string, user: xsd:string, password: xsd:string, service: xsd:string, version: xsd:string
, parameters: xsd:string)
     ns0:wsExecuteResponse(return: xsd:string)
     xsd:ENTITIES
     xsd:ENTITY
     xsd:ID
     xsd:IDREF
     xsd:IDREFS
     xsd:NCName
     xsd:NMTOKEN
     xsd:NMTOKENS
     xsd:NOTATION
     xsd:Name
     xsd:QName
     xsd:anySimpleType
     xsd:anyURI
     xsd:base64Binary
     xsd:boolean
     xsd:byte
     xsd:date
     xsd:dateTime
     xsd:decimal
     xsd:double
     xsd:duration
     xsd:float
     xsd:gDay
     xsd:gMonth
     xsd:gMonthDay
     xsd:gYear
     xsd:gYearMonth
     xsd:hexBinary
     xsd:int
     xsd:integer
     xsd:language
     xsd:long
     xsd:negativeInteger
     xsd:nonNegativeInteger
     xsd:nonPositiveInteger
     xsd:normalizedString
     xsd:positiveInteger
     xsd:short
     xsd:string
     xsd:time
     xsd:token
     xsd:unsignedByte
     xsd:unsignedInt
     xsd:unsignedLong
     xsd:unsignedShort

Bindings:
     Soap11Binding: {http://ws.clients.channels.mw.ksit.com/}AdaptorClientBinding

Service: MWClientEndPointService
     Port: AdaptorClientPort (Soap11Binding: {http://ws.clients.channels.mw.ksit.com/}AdaptorClientBinding)
         Operations:
            wsExecute(channel: xsd:string, user: xsd:string, password: xsd:string, service: xsd:string, version: xsd:str
ing, parameters: xsd:string) -> return: xsd:string

**Comment by mvantellingen** [comment] 2018-01-06 12:36
Closing it since I can't reproduce it due to the fact that the wsdl is unreachable

**Closed by mvantellingen** 2018-01-06 12:36 UTC
