### ISSUE TITLE
Unexpected Encoding Style

### ISSUE THREAD

**Issue by rmevans1** [mvantellingen/python-zeep#843] opened 2018-10-08 17:56 UTC
I am getting the following error: : **caught exception while handling request: unexpected encoding style: expected=http://schemas.xmlsoap.org/soap/encoding/, actual=**

1.  Zeep Version: 3.1.0
2.  WSDL: http://mytest.yrc.com/dynamic/national/WebServices/YRCSecureBOL.wsdl
3. Code Sample (username and password redacted for security)

from zeep import Client
import logging.config
from datetime import datetime

logging.config.dictConfig({
    'version': 1,
    'formatters': {'verbose': {'format': '%(name)s: %(message)s'}},
    'handlers': {'console': {'level': 'DEBUG',
                 'class': 'logging.StreamHandler',
                 'formatter': 'verbose'}},
    'loggers': {'zeep.transports': {'level': 'DEBUG',
                'propagate': True, 'handlers': ['console']}},
    })

endpoint_url = 'http://mytest.yrc.com/dynamic/national/WebServices/YRCSecureBOL.wsdl'
client = Client(endpoint_url)

auth_fields = {'Username': '***', 'Password': '***'}

bol_request = {
    'bolDetail': {
        'pickupDate': datetime.now().strftime('%m') + '/' \
            + datetime.now().strftime('%d') + '/' \
            + datetime.now().strftime('%Y'),
        'role': 'SH',
        'autoSchedulePickup': False,
        'autoEmailBOL': True,
        'autoEmailBOLaddress': '#####@######.com',
        'autoEmailBOLaddress2': '####@######.com',
        'paymentTerms': 'P',
        'originAddressSameAsShipper': True,
        },
    'shipper': {
        'companyName': 'Skutchi Designs, Inc.',
        'address': '1########',
        'city': '######',
        'state': 'SC',
        'zip': '12345',
        'country': 'USA',
        'phoneNumber': '######',
        'businessID': '######',
        },
    'consignee': {
        'companyName': 'Its Just A Link Web Designs',
        'address': '#######',
        'city': 'Walrodf',
        'state': 'MD',
        'zip': '12345',
        'country': 'USA',
        'phoneNumber': '##########',
        },
    'commodityInformation': {'weightTypeIdentifier': 'LB'},
    'commodityItem': [{
        'totalWeight': 1000,
        'handlingUnitQuantity': '1',
        'handlingUnitType': 'PLT',
        'packageQuantity': 10,
        'packageUnitType': 'BOX',
        'productDesc': 'Panels',
        'freightClass': '70',
        'isHazardous': False,
        'length': 48,
        'width': 48,
        'height': 48,
        }],
    'deliveryServiceOptions': {'deliveryServiceOption': 'LTL'},
    'bolLabelPDF': {
        'generateBolPDF': True,
        'bolDocumentType': 'STD',
        'generateShippingLabelsPDF': False,
        'generateProLabelsPDF': False,
        },
    }

response = client.service.submitBOL(UsernameToken=auth_fields,
                                    submitBOLRequest=bol_request)

**Comment by mvantellingen** [comment] 2018-11-18 13:07
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.

**Closed by mvantellingen** 2018-11-18 13:07 UTC

**Comment by munyirik** [comment] 2019-04-03 13:56
@rmevans1 did you find a solution to your problem? 

@mvantellingen, I can be reproduce with:

```
import zeep
wsdl = 'https://sna.etapestry.com/v3messaging/service?WSDL'
client = zeep.Client(wsdl=wsdl)
print(client.service.apiKeyLogin('foo', 'bar'))
```

Result:
```
...
zeep.exceptions.Fault: caught exception while handling request: unexpected encoding style: expected=http://schemas.xmlsoap.org/soap/encoding/, actual=
```

I'm brand new to zeep/soap so any pointers would be greatly appreciated.
