### ISSUE TITLE
Error Parsing WSDL - import issue

### ISSUE THREAD

**Issue by rlamarch** [mvantellingen/python-zeep#276] opened 2016-12-07 14:44 UTC
I'm Running Python 2.7.12 and zeep 0.23.0.  The WSDL is publicly available.

python -m zeep http://services.discretewireless.com/v2009_1/MobileManagerV1.wsdl

It issues a warning that it skips the import DWData.xsd and then fails not finding the element DWHeader which is contained in DWData.  Error is below.  Thanks, Rich

c:\python27\lib\site-packages\zeep\wsdl\wsdl.py:268: ZeepWarning: Skipping import of schema located at 'http://services.
discretewireless.com/v2009_1/xsd/DWData.xsd' for the namespace 'http://services.discretewireless.com/v2009_1/', since th
e namespace was already imported with the schema located at 'http://services.discretewireless.com/v2009_1/xsd/MobileMana
gerV1.xsd'
  self.types.add_documents(schema_nodes, self.location)
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\lib\site-packages\zeep\__main__.py", line 85, in <module>
    main(args)
  File "c:\python27\lib\site-packages\zeep\__main__.py", line 74, in main
    client = Client(args.wsdl_file, transport=transport)
  File "c:\python27\lib\site-packages\zeep\client.py", line 85, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "c:\python27\lib\site-packages\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "c:\python27\lib\site-packages\zeep\wsdl\wsdl.py", line 155, in __init__
    self.messages = self.parse_messages(doc)
  File "c:\python27\lib\site-packages\zeep\wsdl\wsdl.py", line 284, in parse_messages
    msg = parse.parse_abstract_message(self, msg_node)
  File "c:\python27\lib\site-packages\zeep\wsdl\parse.py", line 30, in parse_abstract_message
    part_element = wsdl.types.get_element(part_element)
  File "c:\python27\lib\site-packages\zeep\xsd\schema.py", line 102, in get_element
    return schema.get_element(qname)
  File "c:\python27\lib\site-packages\zeep\xsd\schema.py", line 346, in get_element
    ) % (qname.localname, qname.namespace, known_items or ' - '))
zeep.exceptions.LookupError: No element 'DWHeader' in namespace http://services.discretewireless.com/v2009_1/. Available
 elements are: {http://services.discretewireless.com/v2009_1/}GetDailyMileageByStateByMobileRequest, {http://services.di
scretewireless.com/v2009_1/}GetMobileSensorEventsResponse, {http://services.discretewireless.com/v2009_1/}FindAllFleetsR
esponse, {http://services.discretewireless.com/v2009_1/}FindMobileByIdRequest, {http://services.discretewireless.com/v20
09_1/}AddDriverToMobileResponse, {http://services.discretewireless.com/v2009_1/}GetMobileLocationByIdResponse, {http://s
ervices.discretewireless.com/v2009_1/}GetFleetSensorEventsSinceResponse, {http://services.discretewireless.com/v2009_1/}
FindMobilesByNameRequest, {http://services.discretewireless.com/v2009_1/}InitializeEngineHoursRequest, {http://services.
discretewireless.com/v2009_1/}GetMobilePingsSinceRequest, {http://services.discretewireless.com/v2009_1/}GetMobileFields
Response, {http://services.discretewireless.com/v2009_1/}FindAllMobilesWithAdditionalFieldsResponse, {http://services.di
scretewireless.com/v2009_1/}PingMobilesRequest, {http://services.discretewireless.com/v2009_1/}FindAllMobilesResponse, {
http://services.discretewireless.com/v2009_1/}GetMobilePingsSinceResponse, {http://services.discretewireless.com/v2009_1
/}FindAllFleetsRequest, {http://services.discretewireless.com/v2009_1/}DeleteMobileByIdRequest, {http://services.discret
ewireless.com/v2009_1/}FindMobilesByBeginsWithResponse, {http://services.discretewireless.com/v2009_1/}BooleanResponse,
{http://services.discretewireless.com/v2009_1/}GetMobileSensorEventsBetweenRequest, {http://services.discretewireless.co
m/v2009_1/}GetMobileSensorEventsSinceRequest, {http://services.discretewireless.com/v2009_1/}FindMobilesByDriverNameResp
onse, {http://services.discretewireless.com/v2009_1/}GetAllMobileFieldsRequest, {http://services.discretewireless.com/v2
009_1/}AddMobileResponse, {http://services.discretewireless.com/v2009_1/}CreateMobileFieldRequest, {http://services.disc
retewireless.com/v2009_1/}FindAllMobilesRequest, {http://services.discretewireless.com/v2009_1/}GetFleetSensorEventsSinc
eRequest, {http://services.discretewireless.com/v2009_1/}UpdateMobileFieldRequest, {http://services.discretewireless.com
/v2009_1/}GetAccelerometerEventsRequest, {http://services.discretewireless.com/v2009_1/}FindClosestMobilesToLatLonReques
t, {http://services.discretewireless.com/v2009_1/}GetMobileLocationByIdRequest, {http://services.discretewireless.com/v2
009_1/}FindMobilesByDriverNameRequest, {http://services.discretewireless.com/v2009_1/}UpdateMobileResponse, {http://serv
ices.discretewireless.com/v2009_1/}AddDriverToMobileRequest, {http://services.discretewireless.com/v2009_1/}CUDResponse,
 {http://services.discretewireless.com/v2009_1/}GetDailyMileageByStateByMobileResponse, {http://services.discretewireles
s.com/v2009_1/}InitializeOdometerRequest, {http://services.discretewireless.com/v2009_1/}FindMobileByIdResponse, {http:/
/services.discretewireless.com/v2009_1/}FindMobilesByNameResponse, {http://services.discretewireless.com/v2009_1/}FindAl
lMobilesWithAdditionalFieldsRequest, {http://services.discretewireless.com/v2009_1/}DeleteMobileFieldRequest, {http://se
rvices.discretewireless.com/v2009_1/}GetAccelerometerEventsResponse, {http://services.discretewireless.com/v2009_1/}AddM
obileRequest, {http://services.discretewireless.com/v2009_1/}FindClosestMobilesToLatLonResponse, {http://services.discre
tewireless.com/v2009_1/}UpdateMobileRequest, {http://services.discretewireless.com/v2009_1/}FindMobilesByBeginsWithReque
st, {http://services.discretewireless.com/v2009_1/}PingMobilesResponse, {http://services.discretewireless.com/v2009_1/}G
etMobileDetailsResponse, {http://services.discretewireless.com/v2009_1/}DeleteMobileByIdResponse, {http://services.discr
etewireless.com/v2009_1/}GetMobileDetailsRequest

**Comment by mvantellingen** [comment] 2016-12-09 21:57
This is actually a duplicate of #204  

So i'm closing this one :-)

**Closed by mvantellingen** 2016-12-09 21:57 UTC
