### ISSUE TITLE
Zeep not serializing XML elements 

### ISSUE THREAD

**Issue by jonathanelscpt** [mvantellingen/python-zeep#730] opened 2018-04-17 13:15 UTC
zeep version : 2.5.0

WSDL: https://gist.github.com/jonathanelscpt/4176fe7886576eeb4ef3336fa0fc5a7f
XSD: https://gist.github.com/jonathanelscpt/88442b67440e9871893f1de07a3b0320
ENUM XSD : https://gist.github.com/jonathanelscpt/63119410f8d692cfccf0ea243c2ec5b9

I have a type in the WSLD I'm using that contains an unspecified  number of tags not defined within the WSDL:

```
    <xsd:complexType name="XVendorConfig">
		<xsd:sequence>
			<xsd:any maxOccurs="unbounded" minOccurs="0" namespace="##local" processContents="skip"/>
		</xsd:sequence>
	</xsd:complexType>
    <xsd:complexType name="XContent">
		<xsd:sequence>
			<xsd:any maxOccurs="unbounded" minOccurs="0" namespace="##local" processContents="skip"/>
		</xsd:sequence>
	</xsd:complexType>
```

when this is returned in a number of get requests in the wsdl, the output looks like this:

```
'vendorConfig': {
                '_value_1': [
                    <Element cuetLevel at 0x7effe6810c48>,
                    <Element enableSipDigestAuthentication at 0x7effe6810d08>,
                    <Element cucmGSMHandoffPreference at 0x7effe6810d48>,
                    <Element ldapUseLDAPUserAuthentication at 0x7effe6810d88>,
                    <Element ldapUserName at 0x7effe6810dc8>,
                    <Element ldapPassword at 0x7effe6810e08>,
                    <Element ldapUseSSL at 0x7effe6810e48>,
                    <Element dialerEmergencyNumbers at 0x7effe6810e88>,
                    <Element useStandardRingtone at 0x7effe6810ec8>,
                    <Element minRingtoneVolume at 0x7effe6810f08>,
                    <Element enableDVOFeature at 0x7effe6810f48>,
                    <Element videoCapability at 0x7effe6810f88>
                ]
            }
```

This is not serializable and fails during a json dump.

I would like to extract this information sanely, preferably as a list of k, v pairs, but would like to do so in a way that it would be reuseble for a subsequent requests.

Although its not the only case in the schema, the parent type is:

`<xsd:complexType name="RPhone">`

containing:

`<xsd:element maxOccurs="1" minOccurs="0" name="vendorConfig" type="axlapi:XVendorConfig"/>`

Is there a better way to handle this?

**Comment by mvantellingen** [comment] 2018-07-28 07:40
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.

**Closed by mvantellingen** 2018-07-28 07:40 UTC

**Comment by jonathanelscpt** [comment] 2018-07-28 10:42
Quick question.

You're attributing closure due to the low quality of the report.  I'm following all your guidelines.  It is properly formatted.  I believe that it includes all relevant info.  I'm uncertain why it was closed without requesting additional information, or actually what the problem here is at all.

I appreciate that its open source work.

**Comment by mvantellingen** [comment] 2018-07-28 15:33
The most important part is missing, an example script. Without this I need to craft my own script to reproduce your issue before I can start looking into the issue. This part usually takes most of my time because often assets are not public or part of the problem is the exact way zeep is used. 

I decided to go the ‘hard’ route and close issues as soon as I see that such script is missing. Mostly to reduce the number of open issues with which I won’t be able to do anything. I sometimes might make the wrong decision here, but it allows me to focus more on the fun part of open source

**Comment by jonathanelscpt** [comment] 2018-07-28 15:40
Fair comment.  Will address in future issues.  Thanks for coming back to me here - much appreciated.
