### ISSUE TITLE
zeep.exceptions.TransportError: Server returned HTTP status 415 (b'The server cannot service the request because the media type is unsupported.')

### ISSUE THREAD

**Issue by agrawal-mohit** [mvantellingen/python-zeep#24] opened 2016-05-14 08:57 UTC
Accessing this wsdl - http://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc?wsdl
Here's the code - 

import zeep 
from zeep import Client

location = 'http://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc'
wsdl_url = location+'?wsdl'

userID = 'xxxxx'
password = 'xxxx'
passkey = 'xxxxxxxxx'

result = client.service.getPassword(userID, password, passkey)
print(result)

**Comment by mvantellingen** [comment] 2016-05-14 12:57
This should be fixed with 963cbbf99a80db6ef20c4b8ea111412e01cf03e6

Can you give the master branch a try?

**Comment by mvantellingen** [comment] 2016-05-29 10:08
Duplicate of #35

**Closed by mvantellingen** 2016-05-29 10:08 UTC
Labels: info-required
