### ISSUE TITLE
Namespace prefixes ignored on SOAP responses.

### ISSUE THREAD

**Issue by anaoum** [mvantellingen/python-zeep#164] opened 2016-08-12 02:30 UTC
In certain implementations, the server will ignore the namespace prefixes used in the SOAP request, and use its own prefixes in the `xsi:type` tags of the response. This results in the response failing to parse because `zeep.xsd.Schema` stores its own prefix map and uses this when creating a QName (see `Schema._create_qname()`).

For example, in the following response XML:

```
<?xml version="1.0" encoding="utf-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://api.radioreference.com/soap2">
    <SOAP-ENV:Body>
        <ns1:getTagResponse xmlns:ns1="http://api.radioreference.com/soap2">
            <return xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="tns:tag[1]">
                <item xsi:type="tns:tag">
                    <tagId xsi:type="xsd:int">4</tagId>
                    <tagDescr xsi:type="xsd:string">EMS Dispatch</tagDescr>
                </item>
            </return>
        </ns1:getTagResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

The exception is thrown: `ValueError: No namespace defined for the prefix 'tns'` because this namespace was defined as `ns0` by the Schema in `Schema._create_prefix_map()`.

**Comment by mvantellingen** [comment] 2016-09-12 20:24
Thanks, #184 turned out to be a duplicate of this afaik.

**Closed by mvantellingen** 2016-09-12 20:24 UTC
Labels: bug, xsd
