### ISSUE TITLE
Error while parsing a response

### ISSUE THREAD

**Issue by twanschik** [mvantellingen/python-zeep#153] opened 2016-07-29 13:19 UTC
Hi,
I'm not allowed to post all information, however I try to do my best to describe the problem I'm facing.
Here is the wsdl definition of the response for the ping request of a third party service:

```xml
<definitions name='3rdService' targetNamespace='com.3rd.soap.3rd' xmlns='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:tns='com.3rd.soap.3rd' xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
 <documentation>3rdService</documentation>
 <types>
  <schema targetNamespace='com.3rd.soap.3rd' xmlns='http://www.w3.org/2001/XMLSchema' xmlns:tns='com.3rd.soap.3rd'>
   <complexType name='3rdPingResponse'>
    <complexContent>
     <extension base='tns:3rdResponse'>
      <sequence>
       <element minOccurs='0' name='echoData' nillable='true' type='xsd:string'/>
      </sequence>
     </extension>
    </complexContent>
   </complexType>
   <complexType name='3rdGenericData'>
    <sequence>
     <element minOccurs='0' name='key' nillable='true' type='xsd:string'/>
     <element maxOccurs='unbounded' minOccurs='0' name='values' nillable='true' type='xsd:string'/>
    </sequence>
   </complexType>
   <complexType name='3rdResponse'>
    <sequence>
     <element maxOccurs='unbounded' minOccurs='0' name='genericData' nillable='true' type='tns:3rdGenericData'/>
     <element minOccurs='0' name='traceId' nillable='true' type='xsd:string'/>
     <element minOccurs='0' name='transactionId' nillable='true' type='tns:3rdIdType'/>
    </sequence>
   </complexType>
  </schema>
 </types>
 <message name='3rdSoapService_pingResponse'>
  <part name='pingResponse' type='tns:PingResponse'></part>
 </message>
 <portType name='3rdSoapService'>
  <operation name='ping'>
   <input message='tns:3rdSoapService_pingRequest'></input>
   <output message='tns:3rdSoapService_pingResponse'></output>
   <fault message='tns:3rdException' name='3rdException'></fault>
  </operation>
 </portType>
</definitions>
```

I have no problem doing the ping request using zeep. However, when doing so I get the following response:

```xml
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
 <env:Header>
 </env:Header>
 <env:Body>
  <ns1:pingResponse xmlns:ns1="com.3rd.soap.3rd">
   <pingResponse>
    <echoData>Hello World!</echoData>
   </pingResponse>
  </ns1:pingResponse>
 </env:Body>
</env:Envelope>
```

Zeep can't parse the response. The following exception is raised:

```python
Traceback (most recent call last):
  File "C:/Users/qqq/Documents/Development/myProject/myProject/my_test.py", line 5, in <module>
    session.ping()
  File "C:\Users\qqq\Documents\Development\myProject\mylib\mylib\api.py", line 61, in ping
    'echoData': 'Hello world'}))
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\wsdl\soap.py", line 94, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\wsdl\soap.py", line 125, in process_reply
    return operation.process_reply(doc)
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\wsdl\soap.py", line 258, in process_reply
    return self.output.deserialize(body)
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\wsdl\messages.py", line 274, in deserialize
    result = self.body.parse(value, self.wsdl.types)
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\xsd\elements.py", line 212, in parse
    xmlelement, '{http://www.w3.org/2001/XMLSchema-instance}type')
  File "C:\Users\qqq\Documents\Development\myProject\.venv\lib\site-packages\zeep\utils.py", line 14, in qname_attr
    value = node.get(attr_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

While debugging I found that zeep tries to deserialize the body (i.e. the first line of the method `deserialize()` of the class `RpcMessage` in 'zeep/wsdl/messages.py'). zeep searches for the `3rdSoapService_pingResponse`-message element inside of the `Body`-element but can't find it, leading to `node` being `None`. The response doesn't contain such an element (instead it only contains an `ns1:pingResponse` node). When hardcoding the tag that is searched for from `3rdSoapService_pingResponse` to `pingResponse` everything works fine.

I'm not sure if the response is incorrect or if zeep should be able to handle these kind of problems. Thanks in advance for any help.

**Comment by mvantellingen** [comment] 2016-07-29 13:37
Do you have the definition for "3rdResponse" for me? The 3rdPingResponse type extends from that.

**Comment by twanschik** [comment] 2016-07-29 13:47
Just updated my description to include 3rdResponse.

**Comment by mvantellingen** [comment] 2016-07-31 13:06
I'm not able to reproduce this without a working xsd i'm afraid. Can you check if this works in soap-ui? Otherwise i need a working anonymized minimal wsdl with the corresponding response

**Comment by twanschik** [comment] 2016-08-02 14:23
I tested the request using soap-ui. Everything seems to work correctly. I've attached the minimal anonymized wsdl and the corresponding response.

Thanks for your help.

[anonymized data.zip](https://github.com/mvantellingen/python-zeep/files/397202/anonymized.data.zip)

**Comment by Untou4able** [comment] 2016-08-26 05:21
I ran into the same problem, i am getting response which zeep unable to parse.
That's what i do:
```python
c.service.getListServices(ServiceIdentifiers = {'cpeid': '454C54585C066E7C'})
```
evaluates into:
```xml
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns0="urn:AxessInterface" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:getListServices>
      <ServiceIdentifiers>
        <cpeid>454C54581C0053BD</cpeid>
      </ServiceIdentifiers>
    </ns0:getListServices>
  </soap-env:Body>
</soap-env:Envelope>
```
respond:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
  
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:xsd3="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi3="http://www.w3.org/2001/XMLSchema-instance"
>
<SOAP-ENV:Body >
<ns1:getListServicesResponse xmlns:ns1="urn:AxessInterface">
<message xsi3:type="xsd3:string">OK</message>
<code xsi3:type="xsd3:int">200</code>
<result>
<Services SOAP-ENC:arrayType="ns1:anyStruct[2]" xsi3:type="SOAP-ENC:Array">
<item>
<cid xsi3:type="xsd3:string"></cid>
<cid2 xsi3:type="xsd3:string"></cid2>
<cpeid xsi3:type="xsd3:string">454C54581C0053BD</cpeid>
<creation_time xsi3:type="xsd3:double">1470751933.0</creation_time>
<extServiceid xsi3:type="xsd3:string"></extServiceid>
<last_updated xsi3:type="xsd3:double">1472187288.0</last_updated>
<pending_properties>
<authPassword xsi3:type="xsd3:string"></authPassword>
<authUserName xsi3:nil="true"/>
<lineID xsi3:nil="true"/>
<phoneNumber xsi3:nil="true"/>
<realm xsi3:nil="true"/>
<sVLAN xsi3:nil="true"/>
</pending_properties>
<properties>
<authPassword xsi3:type="xsd3:string"></authPassword>
<authUserName xsi3:type="xsd3:string">123</authUserName>
<lineID xsi3:type="xsd3:integer">1</lineID>
<phoneNumber xsi3:type="xsd3:string">345</phoneNumber>
<realm xsi3:type="xsd3:string"></realm>
<sVLAN xsi3:nil="true"/>
</properties>
<realStatus xsi3:type="xsd3:integer">0</realStatus>
<servicetype xsi3:type="xsd3:string">VOIP</servicetype>
<status xsi3:type="xsd3:integer">1</status>
</item>
<item>
<cid xsi3:type="xsd3:string"></cid>
<cid2 xsi3:type="xsd3:string"></cid2>
<cpeid xsi3:type="xsd3:string">454C54581C0053BD</cpeid>
<creation_time xsi3:type="xsd3:double">1470994013.0</creation_time>
<extServiceid xsi3:type="xsd3:string"></extServiceid>
<last_updated xsi3:type="xsd3:double">1470994029.0</last_updated>
<pending_properties>
<SSID xsi3:nil="true"/>
<channel xsi3:nil="true"/>
<encryption xsi3:nil="true"/>
<id xsi3:nil="true"/>
<key xsi3:nil="true"/>
</pending_properties>
<properties>
<SSID xsi3:type="xsd3:string">NTP-RG_rev.C_ma4000</SSID>
<channel xsi3:type="xsd3:string">Auto</channel>
<encryption xsi3:type="xsd3:string">wpa2</encryption>
<id xsi3:type="xsd3:integer">1</id>
<key xsi3:type="xsd3:string"></key>
</properties>
<realStatus xsi3:type="xsd3:integer">1</realStatus>
<servicetype xsi3:type="xsd3:string">WIFI</servicetype>
<status xsi3:type="xsd3:integer">1</status>
</item>
</Services>
</result>
</ns1:getListServicesResponse>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
which results in:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/wsdl/soap.py", line 92, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/wsdl/soap.py", line 123, in process_reply
    return operation.process_reply(doc)
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/wsdl/soap.py", line 256, in process_reply
    return self.output.deserialize(body)
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/wsdl/messages.py", line 274, in deserialize
    result = self.body.parse(value, self.wsdl.types)
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/xsd/elements.py", line 212, in parse
    xmlelement, '{http://www.w3.org/2001/XMLSchema-instance}type')
  File "/usr/local/lib/python2.7/dist-packages/zeep-0.15.0.dev0-py2.7.egg/zeep/utils.py", line 14, in qname_attr
    value = node.get(attr_name)
AttributeError: 'NoneType' object has no attribute 'get'
```
attaching wsdl, cuz it's rather huge 
[wsdl.zip](https://github.com/mvantellingen/python-zeep/files/438562/wsdl.zip)

**Comment by FrugoFruit90** [comment] 2016-09-01 15:01
I'm starting to think I have the same issue https://github.com/mvantellingen/python-zeep/issues/177

Judging from the following part of traceback in my case, the function seems to break down when dealing with the body:
```
  File "C:\Users\j.zysko\Envs\gabinet\lib\site-packages\zeep\wsdl\soap.py", line 256, in process_reply
    return self.output.deserialize(body)
  File "C:\Users\j.zysko\Envs\gabinet\lib\site-packages\zeep\wsdl\messages.py", line 240, in deserialize
    assert elm is not None, '%s not found' % part.element.qname
```
The problematic XML response is the following:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header>
      <ns1:session id="8376098C176B5AD5E9A14AF2FA07D870" xmlns:ns1="http://xml.kamsoft.pl/ws/common"/>
      <ns1:authToken id="BSLp7AoO_IFHXGite_3gye" xmlns:ns1="http://xml.kamsoft.pl/ws/common"/>
   </soapenv:Header>
   <soapenv:Body>
      <ns1:loginReturn xmlns:ns1="http://xml.kamsoft.pl/ws/kaas/login_types">[000] U&amp;#380;ytkownik zosta&amp;#322; prawid&amp;#322;owo zalogowany.</ns1:loginReturn>
   </soapenv:Body>
</soapenv:Envelope>
```
Does any of you guys know if I could somehow circumvent this before the whole thing gets fixed?
Thing is, I don't really need anything that is inside of the body as I'm only interested in the header.
When I comment out the "assert" line from traceback I get the same error message as you guys:
```
  File "C:\Users\j.zysko\Envs\gabinet\lib\site-packages\zeep\utils.py", line 14, in qname_attr
    value = node.get(attr_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by mvantellingen** [comment] 2016-09-04 22:05
Could you give the master branch a try? fixed some issues related to the parsing of RPC messages

**Comment by mvantellingen** [comment] 2016-09-26 19:13
This is same issue as #180  (closing this one)

**Closed by mvantellingen** 2016-09-26 19:13 UTC
Labels: feedback-required, xsd
