### ISSUE TITLE
wsse header not added?

### ISSUE THREAD

**Issue by nagylzs** [mvantellingen/python-zeep#465] opened 2017-06-10 19:37 UTC
```

from lxml.etree import tostring

from zeep import Client
from zeep.wsse.username import UsernameToken

USERNAME = "some_username"
PASSWORD = "some_password"

client = Client("https://svn.apache.org/repos/asf/juddi/trunk/juddi-client.net/example/WcfServiceLifeCycle/sample.wsdl",
                    wsse=UsernameToken(USERNAME, PASSWORD))
node = client.create_message(client.service, "sayHello", firstName="John")
print(tostring(node, encoding="UTF-8", pretty_print=True).decode("UTF-8"))

```

The following is printed:
```<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:sayHello xmlns:ns0="urn:examples:helloservice">
      <firstName>John</firstName>
    </ns0:sayHello>
  </soap-env:Body>
</soap-env:Envelope>

```

So the envelope contains the body, but it does not contain the wsse headers. 

What am I doing wrong?

**Comment by mvantellingen** [comment] 2017-06-11 16:54
Client.create_message() didn't apply  plugins / wsse. Fixed in master

**Closed by mvantellingen** 2017-06-11 16:54 UTC

**Comment by hmngwy** [comment] 2018-01-02 08:02
@mvantellingen 

WSSE header tags not added when calling `client.service.*()`. Am I missing something?

```
import uuid
import datetime
import zeep
from zeep.wsse.username import UsernameToken
from lxml.builder import ElementMaker
from lxml import etree


from zeep import Plugin


class MyLoggingPlugin(Plugin):

    def ingress(self, envelope, http_headers, operation):
        return envelope, http_headers

    def egress(self, envelope, http_headers, operation, binding_options):
        print(http_headers)
        print(etree.tostring(envelope, encoding='unicode', pretty_print=True))
        return envelope, http_headers


def get_wsa_headers():
    WSA_NS = 'http://schemas.xmlsoap.org/ws/2004/08/addressing'
    return [
        ElementMaker(namespace=WSA_NS).Action(
            'http://ADPNetworkSolutions/CARPort/GetCallsByTime'),
        ElementMaker(namespace=WSA_NS).MessageID(
            'urn:uuid:' + str(uuid.uuid4())),
        ElementMaker(namespace=WSA_NS).To(
            'https://www.mynetworkphone.com/carport/carport.asmx')
    ]


def main():
    now = datetime.datetime.now()
    start = now - datetime.timedelta(minutes=10)
    wsdl = 'https://www.mynetworkphone.com/carport/carport.asmx?WSDL'
    client = zeep.Client(wsdl=wsdl, wsse=UsernameToken(
        'username', 'password'), plugins=[MyLoggingPlugin()])

    start = client.get_type('ns0:GetCallsByTimeRequest')(StartTime=start)
    result = client.service.GetCallsByTime(
        start, _soapheaders=get_wsa_headers())

    for call in result.CallDetailItems.CallLogItem:
        print(call)


if __name__ == '__main__':
    main()
```

This is the output:

```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Header>
    <ns0:Action xmlns:ns0="http://schemas.xmlsoap.org/ws/2004/08/addressing">http://ADPNetworkSolutions/CARPort/GetCallsByTime</ns0:Action>
    <ns0:MessageID xmlns:ns0="http://schemas.xmlsoap.org/ws/2004/08/addressing">urn:uuid:56c5b550-bfe4-4a70-8d6d-0b2340f19b7d</ns0:MessageID>
    <ns0:To xmlns:ns0="http://schemas.xmlsoap.org/ws/2004/08/addressing">https://www.mynetworkphone.com/carport/carport.asmx</ns0:To>
  </soap-env:Header>
  <soap-env:Body>
    <ns0:GetCallsByTime xmlns:ns0="http://ADPNetworkSolutions/CARPort">
      <ns0:request>
        <ns0:StartTime>2018-01-02T15:47:04.701401</ns0:StartTime>
      </ns0:request>
    </ns0:GetCallsByTime>
  </soap-env:Body>
</soap-env:Envelope>
```

**Comment by hmngwy** [comment] 2018-01-04 03:38
It seems it's being added after the `egress` hook in `Plugin`, but it is being added. If that's by design please ignore my comment above.

**Comment by dbjock** [comment] 2019-05-13 15:40
Is it by design that the egress plugin will not provide the wsse header? The Client.create_message() does.

If this is by design, I suggest including that information in the documentation. I can understand why it doesn't for security reasons.
