### ISSUE TITLE
XMLParseError: Unexpected element

### ISSUE THREAD

**Issue by aliadiby** [mvantellingen/python-zeep#779] opened 2018-07-02 14:49 UTC
First of all, thanks a lot for the great library here!

On several wsdl's, i'm getting an error while parsing the XML response.

first occurance of several similar errors
> Unexpected element '{http://fris.ewi.be/}external'

the error can be bypassed by **strict=False** settings, but this results in a return of _raw_elements:

> '_raw_elements': deque([<Element {http://fris.ewi.be/}external at 0x110d49c08>,...

version 3.0.0 (grabbed from pip today(2nd of July))
wsdl: https://frisr3.researchportal.be/ws/PersonServiceFRIS?wsdl

script:
```
def get_person(wsdl, page_size):
    for fnc, v in mainfunc.items():
        if fnc == wsdl:
            for key, value in wsdls.items():
                if key == wsdl:
                    client = zeep.Client(wsdl=value)
                    page_num = 0
                    uuid_type = client.get_type('ns1:textSearchCriteria')
                    name = uuid_type(search='pattyn')
                    request_crit = {'window':
                        {
                            'pageSize': page_size,
                            'pageNumber': page_num,
                            'orderings': {
                                'order': {
                                    'id': 'name',
                                    'locale': 'nl_BE',
                                    'direction': 'ASCENDING',
                                },
                            },
                        }, 'name': name}
                    get_func = getattr(client.service, v)
                    client_result = get_func(request_crit)
                    with open('person_example.txt', 'w') as f:
                        print(client_result, file=f)
```

**Comment by Kunzol** [comment] 2018-07-03 14:02
I assume this is a duplicate of #652

**Comment by aliadiby** [comment] 2018-07-03 14:20
Thank you for your input Kunzol, I think the problem is indeed the same or at least very similar. The difference is that I always get the error on my endpoint and not randomly or occasionally.

> The error and the correct result can not be predicted. Sometimes I have to run it 10 times, before getting the correct result and sometimes it runs 10 times before getting the error.

**Comment by mvantellingen** [comment] 2018-07-28 07:40
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.

**Closed by mvantellingen** 2018-07-28 07:40 UTC
