### ISSUE TITLE
zeep.exceptions.TransportError: Server returned HTTP status 415 (b'The server cannot service the request because the media type is unsupported.')

### ISSUE THREAD

**Issue by agrawal-mohit** [mvantellingen/python-zeep#35] opened 2016-05-26 08:10 UTC
Trying to access this web service : 

from zeep import Client
from zeep.transports import Transport

location = 'http://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc'
wsdl_url = location+'?wsdl'

transport = Transport(verify=False)
client = Client(wsdl_url, transport=transport)

userID = '1003201'
password = 'test@123'
passkey = 'test123'

result = client.service.getPassword(userID, password, passkey)
print(result)

This is the trace I get when I run this script : 

Traceback (most recent call last):
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/soap.py", line 85, in process_reply
    doc = fromstring(response.content)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/defusedxml/lxml.py", line 140, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94853)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zeep_test.py", line 19, in <module>
    result = client.service.getPassword(userID, password, passkey)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/client.py", line 24, in __call__
    self._proxy._client, self._op_name, args, kwargs)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/definitions.py", line 284, in send
    client, self.binding_options, operation, args, kwargs)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/soap.py", line 73, in send
    return self.process_reply(client, operation_obj, response)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/soap.py", line 89, in process_reply
    % (response.status_code, response.content))
zeep.exceptions.TransportError: Server returned HTTP status 415 (b'The server cannot service the request because the media type is unsupported.')

What's going wrong here ?

**Comment by mvantellingen** [comment] 2016-05-26 08:31
Which version are you using? I'm not able to reproduce this

**Comment by agrawal-mohit** [comment] 2016-05-28 09:43
zeep-0.6.0

What do you get in result ?

**Comment by agrawal-mohit** [comment] 2016-05-28 09:46
Now I am getting this trace :


Traceback (most recent call last):
  File "test2.py", line 20, in <module>
    result = client.service.getPassword(userID, password, passkey)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/client.py", line 23, in __call__
    self._proxy._client, self._op_name, args, kwargs)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/definitions.py", line 271, in send
    client, self.binding_options, operation, args, kwargs)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/soap.py", line 60, in send
    return self.process_reply(client, operation_obj, response)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/soap.py", line 82, in process_reply
    return self.process_error(doc)
  File "/Users/mohit/anaconda3/envs/py34/lib/python3.4/site-packages/zeep/wsdl/soap.py", line 106, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: None

**Comment by mvantellingen** [comment] 2016-05-29 09:57
I've just committed a change which parses the returned Fault response correctly for Soap 1.2

The issue however seems to be that zeep doesn't (yet) support ws-addressing

**Comment by mvantellingen** [comment] 2016-06-02 19:15
Closing for now, feel free to re-open it if it still gives problems

**Closed by mvantellingen** 2016-06-02 19:15 UTC
Labels: feedback-required
